# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_navigate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navigate',
        ),
    ]
