# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_navigate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name=b'\xe5\xaf\xbc\xe8\x88\xaa\xe5\x90\x8d\xe7\xa7\xb0')),
                ('description', models.CharField(max_length=50, verbose_name=b'\xe5\xaf\xbc\xe8\x88\xaa\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('navurl', models.CharField(max_length=64, verbose_name=b'url')),
                ('show', models.BooleanField(default=True, help_text=b'\xe8\x8f\x9c\xe5\x8d\x95\xe6\x98\xaf\xe5\x90\xa6\xe6\x98\xbe\xe7\xa4\xba\xef\xbc\x8c\xe9\xbb\x98\xe8\xae\xa4\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x98\xbe\xe7\xa4\xba', verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x98\xbe\xe7\xa4\xba')),
                ('sub', models.BooleanField(default=False, help_text=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x9c\x89\xe5\xad\x90\xe8\x8f\x9c\xe5\x8d\x95\xef\xbc\x8c\xe9\xbb\x98\xe8\xae\xa4\xe6\xb2\xa1\xe6\x9c\x89\xe5\xad\x90\xe8\x8f\x9c\xe5\x8d\x95', verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x9c\x89\xe5\xad\x90\xe8\x8f\x9c\xe5\x8d\x95')),
                ('index', models.IntegerField(default=999, verbose_name=b'\xe6\x8e\x92\xe5\x88\x97\xe9\xa1\xba\xe5\xba\x8f(\xe4\xbb\x8e\xe5\xb0\x8f\xe5\x88\xb0\xe5\xa4\xa7)')),
                ('pid', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Navigate', verbose_name=b'\xe7\x88\xb6\xe7\xba\xa7\xe8\x8f\x9c\xe5\x8d\x95')),
            ],
            options={
                'ordering': ['index', 'id'],
                'verbose_name': '\u5bfc\u822a',
                'verbose_name_plural': '\u5bfc\u822a',
            },
        ),
    ]
